### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by hardeecious** [college-of-southern-idaho/blackboard-quiz-generator#3]
As teachers, we are not really familiarized with this thing about coding, programming or running files. So far, I could only understand that users need to download a file and to put it in the root of something...I don't know what. I couldn't file the name or a link to download the tool itself.  This is hard to understand. Please, can you provide, at least, a detailed guide step by step on what to download first, what to run next and so on? All your help would be much appreciated.

**Comment by StellaJaneRasmussen** [comment]
Hello! This tool will be something that most-likely needs to be installed by your IT department, as it's a web application that's dependent upon a web server.

**Comment by StellaJaneRasmussen** [comment]
If your IT department setting this up needs further instructions, I'd be happy to provide that, but this will be a difficult tool to get set up on your own.

If you don't have an IT department, I can provide some instructions for using this tool locally, but it will be a decently involved set up.
